# src/Rw/BlogBundle/Resources/config/routing.yml
rwblog_home:
    path:      /{page}
    defaults:  { _controller: RwBlogBundle:Blog:index, page: 1 }
    requirements:
        page:  \d*		

rwblog_list:
    path:      /list/{page}
    defaults:  { _controller: RwBlogBundle:Blog:list, page: 1 }
    requirements:
        page:  \d*	

rwblog_view:
    path:      /billet/{id}
    defaults:  { _controller: RwBlogBundle:Blog:view }
    requirements:
        id:  \d+
    
rwblog_add:
    path:      /add
    defaults:  { _controller: RwBlogBundle:Blog:add }

rwblog_edit:
    path:      /edit/{id}
    defaults:  { _controller: RwBlogBundle:Blog:edit }
    requirements:
        id:  \d+

rwblog_delete:
    path:      /delete/{id}
    defaults:  { _controller: RwBlogBundle:Blog:delete }
    requirements:
        id:  \d+
rwblog_add_comment:
    path:  /comment/{id}
    defaults: { _controller: RwBlogBundle:Blog:addComment }
    requirements:
        id:      \d+
rwblog_edit_comment:
    path:  /comment/edit/{id}
    defaults: { _controller: RwBlogBundle:Blog:editComment }
    requirements:
        id:      \d+
rwblog_delete_comment:
    path:  /comment/delete/{id}
    defaults: { _controller: RwBlogBundle:Blog:deleteComment }
    requirements:
        id:      \d+