<?php

namespace Rw\CoreBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PoliceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PoliceRepository extends EntityRepository
{
}
