<?php

namespace Rw\CoreBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * Police2Repository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Police2Repository extends EntityRepository
{
}
